name: Create Release
description: "Creates a release"

inputs:
  version:
    description: "The tag name for the release"
    required: true
  prerelease:
    description: "Whether the release is a pre-release"
    required: true
  github_token:
    description: "The GitHub token"
    required: true
  project_name:
    description: "The name of the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all tags
      shell: bash
      run: git fetch --tags

    - name: Get last full release
      id: get_last_full_release
      shell: bash
      run: |
        LAST_FULL_RELEASE=$(git tag --sort=-v:refname | grep -vE '(-pre|-rc)' | head -n 1)
        echo "LAST_FULL_RELEASE=$LAST_FULL_RELEASE" >> $GITHUB_ENV
        echo "Last full release: $LAST_FULL_RELEASE"

    - name: Generate comprehensive changelog
      shell: bash
      run: |
        if [ -z "${{ env.LAST_FULL_RELEASE }}" ]; then
          echo "No previous full release found. Generating changelog for all commits..."
          git log --oneline > changelog.txt
        else
          echo "Generating changelog since last full release: $LAST_FULL_RELEASE"
          git log "$LAST_FULL_RELEASE"..HEAD --oneline > changelog.txt
        fi

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        prerelease: ${{ inputs.prerelease }}
        name: "${{inputs.project_name}} - Release ${{ inputs.version }}"
        body_path: changelog.txt
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
