name: Create Release
description: "Creates a release"

inputs:
  version:
    description: "The tag name for the release"
    required: true
  prerelease:
    description: "Whether the release is a pre-release"
    required: true
  github_token:
    description: "The GitHub token"
    required: true
  project_name:
    description: "The name of the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all tags
      shell: bash
      run: git fetch --tags

    - name: Get last full release
      shell: bash
      run: |
        # Fetch tags and filter out pre-release or release-candidate tags
        git tag --sort=-v:refname | grep -vE '(-pre|-rc)' | head -n 1 || echo "No previous full release found"

    - name: Generate comprehensive changelog
      shell: bash
      run: |
        if [ "${{ env.LAST_FULL_RELEASE }}" == "all-tags" ]; then
          # No previous release found, generate changelog for all tags
          echo "Generating changelog for all tags..."
          git log --oneline > changelog.txt
        else
          # Generate changelog based on the last full release tag
          echo "Changes since $LAST_FULL_RELEASE"
          git log --oneline "$LAST_FULL_RELEASE"..HEAD > changelog.txt
        fi

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        prerelease: ${{ inputs.prerelease }}
        name: "${{inputs.project_name}} - Release ${{ inputs.version }}"
        body_path: changelog.txt
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
