name: Create Release
description: "Creates or updates a rolling pre-release and promotes it to a final release when needed"

inputs:
  version:
    description: "The tag name for the release"
    required: true
  prerelease:
    description: "Whether the release is a pre-release"
    required: true
  github_token:
    description: "The GitHub token"
    required: true
  project_name:
    description: "The name of the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Find Latest Pre-release
      id: find_pre_release
      run: |
        LATEST_PRE_RELEASE_TAG=$(gh release list --json tagName,isPrerelease,publishedAt \
          --limit 100 -q '[.[] | select(.isPrerelease == true)] | sort_by(.publishedAt) | reverse | .[0].tagName' || echo "")

        if [[ -n "$LATEST_PRE_RELEASE_TAG" ]]; then
          RELEASE_ID=$(gh release view "$LATEST_PRE_RELEASE_TAG" --json id,body -q '.id')
          RELEASE_NOTES=$(gh release view "$LATEST_PRE_RELEASE_TAG" --json body -q '.body')

          echo "release_id=$RELEASE_ID" >> $GITHUB_ENV
          echo "release_tag=$LATEST_PRE_RELEASE_TAG" >> $GITHUB_ENV
          echo "release_notes<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Promote Pre-release to Final Release
      if: env.release_id != '' && inputs.prerelease == 'false'
      run: |
        gh release edit ${{ env.release_tag }} \
          --prerelease=false \
          --notes "$release_notes"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Update Existing Pre-release
      if: env.release_id != '' && inputs.prerelease == 'true'
      run: |
        gh release edit ${{ env.release_tag }} \
          --prerelease
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Create New Pre-release
      if: env.release_id == ''
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        prerelease: ${{ inputs.prerelease }}
        name: "${{ inputs.project_name }} - Release
