name: Create Release
description: "Creates a release"

inputs:
  version:
    description: "The tag name for the release"
    required: true
  prerelease:
    description: "Whether the release is a pre-release"
    required: true
  github_token:
    description: "The GitHub token"
    required: true
  project_name:
    description: "The name of the release"
    required: true
  target_commitish:
    description: "The commitish value that determines where the Git tag is created"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate required inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          echo "Missing required input: version"
          exit 1
        fi
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "Missing required input: github_token"
          exit 1
        fi
        if [ -z "${{ inputs.project_name }}" ]; then
          echo "Missing required input: project_name"
          exit 1
        fi
        if [ -z "${{ inputs.target_commitish }}" ]; then
          echo "Missing required input: target_commitish"
          exit 1
        fi
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        prerelease: ${{ inputs.prerelease }}
        name: "${{inputs.project_name}} - Release ${{ inputs.version }}"
        generate_release_notes: "true"
        target_commitish: ${{ inputs.target_commitish}}  
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
