name: Create Release
description: "Creates or updates a rolling pre-release and promotes it to a final release when needed"

inputs:
  version:
    description: "The tag name for the release"
    required: true
  prerelease:
    description: "Whether the release is a pre-release"
    required: true
  github_token:
    description: "The GitHub token"
    required: true
  project_name:
    description: "The name of the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Find Latest Pre-release
      id: find_pre_release
      run: |
        LATEST_PRE_RELEASE=$(gh release list --json id,tagName,isPrerelease -q '[.[] | select(.isPrerelease == true)] | sort_by(.tagName) | reverse | .[0]')
        RELEASE_ID=$(echo "$LATEST_PRE_RELEASE" | jq -r '.id // empty')
        RELEASE_TAG=$(echo "$LATEST_PRE_RELEASE" | jq -r '.tagName // empty')

        echo "release_id=$RELEASE_ID" >> $GITHUB_ENV
        echo "release_tag=$RELEASE_TAG" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Promote Pre-release to Final Release
      if: env.release_id != '' && inputs.prerelease == 'false'
      run: |
        gh release edit ${{ env.release_tag }} \
          --prerelease=false \
          --draft=false \
          --generate-notes
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Update Existing Pre-release
      if: env.release_id != '' && inputs.prerelease == 'true'
      run: |
        gh release edit ${{ env.release_tag }} \
          --prerelease=true \
          --generate-notes
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash

    - name: Create New Pre-release
      if: env.release_id == ''
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        prerelease: ${{ inputs.prerelease }}
        name: "${{ inputs.project_name }} - Release ${{ inputs.version }}"
        generate_release_notes: "true"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
