name: "build-publish-docker"

description: "Builds and pushes a Docker image to a registry with caching."

inputs:
  registry:
    description: "Docker registry to push the image to"
    required: true
  image_name:
    description: "Name of the Docker image"
    required: true
  registry-username:
    description: username of registry
    required: true
  version:
    description: "Version tag for the image"
    required: true
  registry_password:
    description: "acr password for docker login"
    required: true
  dockerfile_context:
    description: "Dockerfile context"
    required: true

runs:
  using: "composite"

  steps:
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.registry_password }}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=raw,value={{branch}}-{{sha}}-${{inputs.version}},enable={{is_default_branch}},priority=80
          type=raw,value={{branch}}-latest,priority=0
          type=raw,value=${{inputs.version}}
   
    - name: Set Environment Variable
      run: echo "DOCKER_IMAGE=${{ fromJson(steps.meta.outputs.json).tags[0] }}" >> $GITHUB_ENV
      shell: bash

    - uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.dockerfile_context }}
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:buildcache
        cache-to: type=registry,ref=${{  inputs.registry }}/${{ inputs.image_name }}:buildcache,mode=max


