name: "Docker Build and Push"

description: "Builds and pushes a Docker image to a registry with caching."

inputs:
  registry:
    description: "Docker registry to push the image to"
    required: true
  image_name:
    description: "Name of the Docker image"
    required: true
  version:
    description: "Version tag for the image"
    required: true
  acr_password:
    description: "acr password for docker login"
    required: true
  dockerfile_path:
    description: "Path where dockerfile is"
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: studium33
        password: ${{ inputs.acr_password }}

    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=raw,value={{branch}}-{{sha}}-${{inputs.version}},enable={{is_default_branch}},priority=80
          type=raw,value={{branch}}-latest,priority=0

    - name: Set outputs to environment variables
      run: |
        echo "TAGS=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
        echo "LABELS=${{ steps.meta.outputs.labels }}" >> $GITHUB_ENV
      shell: bash

