name: create-version
description: "Creates release version based on latest git commit date"

outputs:
  version_full:
    description: "Full version eg: 25.6.9.1342"
    value: ${{ steps.set_output.outputs.version_full }}
  version_short:
    description: "Short version eg: 25.6.9.13"
    value: ${{ steps.set_output.outputs.version_short }}

runs:
  using: "composite"
  steps:
    - id: set_output
      run: |
        VERSION_FULL=$(git log -1 --format="%at" | xargs -I{} date -d @{} +%y.%-m.%-d.%-H%M)
        VERSION_SHORT=$(git log -1 --format="%at" | xargs -I{} date -d @{} +%y.%-m.%-d.%-H)

        echo "version_full=$VERSION_FULL" >> $GITHUB_OUTPUT
        echo "version_short=$VERSION_SHORT" >> $GITHUB_OUTPUT
      shell: bash

    - run: |
        echo version_full=${{ steps.set_output.outputs.version_full }}
        echo version_short=${{ steps.set_output.outputs.version_short }}
        echo runner.os=${{ runner.os }}
      shell: bash
